version: "3.8"

services:
  postgres:
    image: postgres
    container_name: user
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: hajox245
      POSTGRES_DB: todo
    ports:
      - "50432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
